sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy()
    sprite.destroy()
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (sprites.readDataNumber(otherSprite, "Hit Code") == 0) {
        Shield.value += -0.5
        Health_Bar.value += -20 / Shield.value
        otherSprite.destroy()
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    sprite.destroy(effects.warmRadial, 500)
    Shield.value += -1
    Health_Bar.value += -100 / Shield.value
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (sprites.readDataNumber(sprite, "Hit Code") == 1) {
        info.setScore(info.score() + 1)
        otherSprite.destroy()
        sprite.destroy()
    }
})
let Enemy: Sprite = null
let EP: Sprite = null
let Lazer: Sprite = null
let Shield: StatusBarSprite = null
let Health_Bar: StatusBarSprite = null
let PlayerShip = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................aa..............
    ...............aaaa.............
    ..............aaaaaa............
    .............aaaaaaaa...........
    ............aaaaffaaaa..........
    ...........aaaaffffaaaa.........
    ...........aaaaffffaaaa.........
    ...........aaaaffffaaaa.........
    ...........aaaaffffaaaa.........
    ...........aaaaaffaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...........aaaaaaaaaaaa.........
    ...............bbbbb............
    ...............bbbbb............
    ...............bbbbb............
    ................................
    ...............99999............
    ................................
    ................................
    `, SpriteKind.Player)
let lazy_coder_var: Image
lazy_coder_var = img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .............f..22..f...........
    .............f.2222.f...........
    .............f222222f...........
    .............22222222...........
    ............2222ff2222..........
    ...........2222ffff2222.........
    ...........2222ffff2222.........
    ...........2222ffff2222.........
    ...........2222ffff2222.........
    ...........22222ff22222.........
    ...........222222222222.........
    ...........222222222222.........
    ...........222222222222.........
    ...........222222222222.........
    ...........222222222222.........
    ...........222222222222.........
    ...........222222222222.........
    ...............bbbbb............
    ...............bbbbb............
    ...............bbbbb............
    ................................
    ...............33333............
    ................................
    ................................
    `
lazy_coder_var.flipY()
let counterX: number
let counterY: number
let VX: number
let VY: number
let MS: number
VY = 0
VX = 0
MS = 2
PlayerShip.setPosition(scene.screenWidth() / 2, scene.screenHeight() / 1.2)
info.setScore(0)
Health_Bar = statusbars.create(20, 4, StatusBarKind.Health)
Health_Bar.setLabel("HP")
Health_Bar.attachToSprite(PlayerShip)
Shield = statusbars.create(20, 4, StatusBarKind.Health)
Shield.setLabel("DP")
Shield.attachToSprite(PlayerShip)
Shield.setOffsetPadding(0, 10)
Shield.setColor(9, 2)
Health_Bar.max = 100
Health_Bar.value = 100
Shield.max = 10
Shield.value = 10
forever(function () {
    controller.moveSprite(PlayerShip)
})
forever(function () {
    if (controller.A.isPressed()) {
        Lazer = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 8 . . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . . 8 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, PlayerShip, 0, -100)
        Lazer.setPosition(PlayerShip.x + 7, PlayerShip.y - 5)
        Lazer = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 8 . . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . 8 9 8 . . . . . . . 
            . . . . . . . 8 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, PlayerShip, 0, -100)
        Lazer.setPosition(PlayerShip.x - 5, PlayerShip.y - 5)
        pause(500)
        sprites.setDataNumber(Lazer, "Hit Code", 1)
    }
})
forever(function () {
    EP = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 2 . . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . 2 3 2 . . . . . . . 
        . . . . . . . 2 . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Enemy, 0, 50)
    EP.y += 10
    sprites.setDataNumber(EP, "Hit Code", 0)
    pause(1000)
})
forever(function () {
    Enemy = sprites.create(lazy_coder_var, SpriteKind.Enemy)
    Enemy.setPosition(randint(0, 160), 0)
    Enemy.setVelocity(0, randint(5, 25))
    pause(randint(1500, 2500))
})
forever(function () {
    music.playMelody(music.convertRTTTLToMelody("Galaga:d=4,o=5,b=125:8g4,32c,32p,8d,32f,32p,8e,32c,32p,8d,32a,32p,8g,32c,32p,8d,32f,32p,8e,32c,32p,8g,32b,32p,8c6,32a#,32p,8g#,32g,32p,8f,32d#,32p,8d,32a#4,32p,8a#,32c6,32p,8a#,32g,32p,16a,16f,16d,16g,16e,16d"), 120)
})
